spring:
  #  jackson:
  #    default-property-inclusion: non_null
  profiles:
    active: release

---
server:
  port: 8082
  servlet:
    context-path: /qy
spring:
  config:
    activate:
      on-profile: release
  #  jackson:
  #    default-property-inclusion: non_null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qy-supplier-platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&useAffectedRows=true
#    username: jzkj
#    password: ENC(ir17WBESWEKOuOMcqD943a4HOfx0GjeVh9FV4Jwz+MM=)
    initialSize: 20
    minIdle: 10
    maxActive: 40
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    username: root
    password: root
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: com.jaezi.web.config.NoResultSetOutImpl
    call-setters-on-nulls: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: trace

minio:
  url: http://127.0.0.1:59000
  username: 7JbuKxcGtmkvVDap/ziFow==
  password: IFWAQ3WI85jzTaqhmNVh6LvP3Lfb7OQEcLQXZ5ZLTlFm/zg0sFRNf4YGZj8JuQYo

weChat:
  appId: wx7f41fe70cef70c37
  secret: 05b08fc6302e29baa0591efee807a396
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={0}&secret={1}
  templateUrl: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token={0}
  userUrl: https://api.weixin.qq.com/cgi-bin/user/get?access_token={0}&next_openid={1}
  userInfoUrl: https://api.weixin.qq.com/cgi-bin/user/info/batchget?access_token={0}
  openId: o7n5d50Qy9XGilXeTCn9pFxDIU4U

license:
  open: false
  licensePath: /lic.qy